version: '3.4'

services:
        app:
                tty: true
                stdin_open: true
                build:
                        context: .
                        dockerfile: Dockerfile
                command: bash -c "bundle install && yarn install --check-files && bundle exec rails s -p 3000 -b '0.0.0.0'" 
                depends_on:
                        - database
                ports:
                        - "3000:3000"
                volumes:
                        - .:/app
                        - gem_cache:/usr/local/bundel/gems
                        - node_modules:/app/node_modules
                env_file: .env
                environment:
                        RAILS_ENV: development

        database:
                image: postgres:12.1
                volumes:
                        - db_data:/var/lib/postgresql/data
                        - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
        gem_cache:
        db_data:
        node_modules:
